const ActionType = {
    REGISTER_USER: 'REGISTER_USER',
    REGISTER_COOKER: 'REGISTER_COOKER',
    ERROR_LOGIN: 'ERROR_LOGIN',
    HOME_COMMENTS: 'HOME_COMMENTS',
    HOME_MENUS: 'HOME_MENUS',
    LOGOUT: 'LOGOUT',
    OPEN_LOGIN: 'OPEN_LOGIN',
    CHEF_MENU: 'CHEF_MENU',
    SELECT_MENU: 'SELECT_MENU',
    FILTER_MENU: 'FILTER_MENU',
    UPDATE_USER: 'UPDATE_USER',
    UPDATE_COOKER: 'UPDATE_COOKER',
    MENUS_COOKER: 'MENUS_COOKER',
    CREATE_MENU: 'CREATE_MENU',
    REMOVE_MENU: 'REMOVE_MENU',
    GET_MENU: 'GET_MENU',
    UPDATE_MENU: 'UPDATE_MENU',
    BOOKING_DATE: 'BOOKING_DATE',
    ADD_COMMENT: 'ADD_COMMENT',
    BOOKING_MENU: 'BOOKING_MENU'
};

export default ActionType;