const ActionType = {
    REGISTER_USER: 'REGISTER_USER',
    REGISTER_COOKER: 'REGISTER_COOKER',
    ERROR_LOGIN: 'ERROR_LOGIN',
    HOME_COMMENTS: 'HOME_COMMENTS',
    HOME_MENUS: 'HOME_MENUS',
    LOGOUT: 'LOGOUT',
    OPEN_LOGIN: 'OPEN_LOGIN',
    CHEF_MENU: 'CHEF_MENU',
    SELECT_MENU: 'SELECT_MENU',
    FILTER_MENU: 'FILTER_MENU'
};

export default ActionType;